export const sports = [
  {
    front: 'Soccer',
    back: 'soccer',
    teams: [
      { front: 'Real Madrid', back: 'Real Madrid' },
      { front: 'Barcelona', back: 'Barcelona' },
      { front: 'Manchester United', back: 'Manchester United' },
      { front: 'Manchester City', back: 'Manchester City' },
      { front: 'Liverpool', back: 'Liverpool' },
      { front: 'Chelsea', back: 'Chelsea' },
      { front: 'Arsenal', back: 'Arsenal' },
      { front: 'Tottenham Hotspur', back: 'Tottenham Hotspur' },
      { front: 'Bayern Munich', back: 'Bayern Munich' },
      { front: 'Borussia Dortmund', back: 'Borussia Dortmund' },
      { front: 'Paris Saint-Germain Academy', back: 'Paris Saint-Germain Academy' },
      { front: 'Marseille', back: 'Marseille' },
      { front: 'Juventus', back: 'Juventus' },
      { front: 'AC Milan', back: 'AC Milan' },
      { front: 'Inter Milan', back: 'Inter Milan' },
      { front: 'Napoli', back: 'Napoli' },
      { front: 'Ajax', back: 'Ajax' },
      { front: 'FC Porto', back: 'FC Porto' },
      { front: 'Sporting CP', back: 'Sporting CP' },
      { front: 'Benfica', back: 'Benfica' }
    ]
  },
  {
    front: 'Formula 1',
    back: 'f1',
    teams: [
      { front: 'Oracle Red Bull Racing', back: 'Oracle Red Bull Racing' },
      { front: 'Mercedes-AMG PETRONAS', back: 'Mercedes-AMG PETRONAS Formula One Team' },
      { front: 'Scuderia Ferrari HP', back: 'Scuderia Ferrari HP' },
      { front: 'McLaren', back: 'McLaren Formula 1 Team' },
      { front: 'Aston Martin Aramco', back: 'Aston Martin Aramco Formula One Team' },
      { front: 'BWT Alpine', back: 'BWT Alpine Formula One Team' },
      { front: 'Williams Racing', back: 'Williams Racing' },
      { front: 'MoneyGram Haas', back: 'MoneyGram Haas F1 Team' },
      { front: 'Visa Cash App Racing Bulls', back: 'Visa Cash App Racing Bulls Formula One Team' },
      { front: 'Stake F1 Team Kick Sauber', back: 'Stake F1 Team Kick Sauber' }
    ]
  },
  {
    front: 'NFL',
    back: 'nfl',
    teams: [
      { front: 'Arizona Cardinals', back: 'Arizona Cardinals' },
      { front: 'Atlanta Falcons', back: 'Atlanta Falcons' },
      { front: 'Baltimore Ravens', back: 'Baltimore Ravens' },
      { front: 'Buffalo Bills', back: 'Buffalo Bills' },
      { front: 'Carolina Panthers', back: 'Carolina Panthers' },
      { front: 'Chicago Bears', back: 'Chicago Bears' },
      { front: 'Cincinnati Bengals', back: 'Cincinnati Bengals' },
      { front: 'Cleveland Browns', back: 'Cleveland Browns' },
      { front: 'Dallas Cowboys', back: 'Dallas Cowboys' },
      { front: 'Denver Broncos', back: 'Denver Broncos' },
      { front: 'Detroit Lions', back: 'Detroit Lions' },
      { front: 'Green Bay Packers', back: 'Green Bay Packers' },
      { front: 'Houston Texans', back: 'Houston Texans' },
      { front: 'Indianapolis Colts', back: 'Indianapolis Colts' },
      { front: 'Jacksonville Jaguars', back: 'Jacksonville Jaguars' },
      { front: 'Kansas City Chiefs', back: 'Kansas City Chiefs' },
      { front: 'Las Vegas Raiders', back: 'Las Vegas Raiders' },
      { front: 'Los Angeles Chargers', back: 'Los Angeles Chargers' },
      { front: 'Los Angeles Rams', back: 'Los Angeles Rams' },
      { front: 'Miami Dolphins', back: 'Miami Dolphins' },
      { front: 'Minnesota Vikings', back: 'Minnesota Vikings' },
      { front: 'New England Patriots', back: 'New England Patriots' },
      { front: 'New Orleans Saints', back: 'New Orleans Saints' },
      { front: 'New York Giants', back: 'New York Giants' },
      { front: 'New York Jets', back: 'New York Jets' },
      { front: 'Philadelphia Eagles', back: 'Philadelphia Eagles' },
      { front: 'Pittsburgh Steelers', back: 'Pittsburgh Steelers' },
      { front: 'San Francisco 49ers', back: 'San Francisco 49ers' },
      { front: 'Seattle Seahawks', back: 'Seattle Seahawks' },
      { front: 'Tampa Bay Buccaneers', back: 'Tampa Bay Buccaneers' },
      { front: 'Tennessee Titans', back: 'Tennessee Titans' },
      { front: 'Washington Commanders', back: 'Washington Commanders' }
    ]
  },
  {
    front: 'NBA',
    back: 'nba',
    teams: [
      { front: 'Atlanta Hawks', back: 'Atlanta Hawks' },
      { front: 'Boston Celtics', back: 'Boston Celtics' },
      { front: 'Brooklyn Nets', back: 'Brooklyn Nets' },
      { front: 'Charlotte Hornets', back: 'Charlotte Hornets' },
      { front: 'Chicago Bulls', back: 'Chicago Bulls' },
      { front: 'Cleveland Cavaliers', back: 'Cleveland Cavaliers' },
      { front: 'Dallas Mavericks', back: 'Dallas Mavericks' },
      { front: 'Denver Nuggets', back: 'Denver Nuggets' },
      { front: 'Detroit Pistons', back: 'Detroit Pistons' },
      { front: 'Golden State Warriors', back: 'Golden State Warriors' },
      { front: 'Houston Rockets', back: 'Houston Rockets' },
      { front: 'Indiana Pacers', back: 'Indiana Pacers' },
      { front: 'Los Angeles Clippers', back: 'Los Angeles Clippers' },
      { front: 'Los Angeles Lakers', back: 'Los Angeles Lakers' },
      { front: 'Memphis Grizzlies', back: 'Memphis Grizzlies' },
      { front: 'Miami Heat', back: 'Miami Heat' },
      { front: 'Milwaukee Bucks', back: 'Milwaukee Bucks' },
      { front: 'Minnesota Timberwolves', back: 'Minnesota Timberwolves' },
      { front: 'New Orleans Pelicans', back: 'New Orleans Pelicans' },
      { front: 'New York Knicks', back: 'New York Knicks' },
      { front: 'Oklahoma City Thunder', back: 'Oklahoma City Thunder' },
      { front: 'Orlando Magic', back: 'Orlando Magic' },
      { front: 'Philadelphia 76ers', back: 'Philadelphia 76ers' },
      { front: 'Phoenix Suns', back: 'Phoenix Suns' },
      { front: 'Portland Trail Blazers', back: 'Portland Trail Blazers' },
      { front: 'Sacramento Kings', back: 'Sacramento Kings' },
      { front: 'San Antonio Spurs', back: 'San Antonio Spurs' },
      { front: 'Toronto Raptors', back: 'Toronto Raptors' },
      { front: 'Utah Jazz', back: 'Utah Jazz' },
      { front: 'Washington Wizards', back: 'Washington Wizards' }
    ]
  },
  {
    front: 'MLB',
    back: 'mlb',
    teams: [
      { front: 'Arizona Diamondbacks', back: 'Arizona Diamondbacks' },
      { front: 'Atlanta Braves', back: 'Atlanta Braves' },
      { front: 'Baltimore Orioles', back: 'Baltimore Orioles' },
      { front: 'Boston Red Sox', back: 'Boston Red Sox' },
      { front: 'Chicago White Sox', back: 'Chicago White Sox' },
      { front: 'Chicago Cubs', back: 'Chicago Cubs' },
      { front: 'Cincinnati Reds', back: 'Cincinnati Reds' },
      { front: 'Cleveland Guardians', back: 'Cleveland Guardians' },
      { front: 'Colorado Rockies', back: 'Colorado Rockies' },
      { front: 'Detroit Tigers', back: 'Detroit Tigers' },
      { front: 'Houston Astros', back: 'Houston Astros' },
      { front: 'Kansas City Royals', back: 'Kansas City Royals' },
      { front: 'Los Angeles Angels', back: 'Los Angeles Angels' },
      { front: 'Los Angeles Dodgers', back: 'Los Angeles Dodgers' },
      { front: 'Miami Marlins', back: 'Miami Marlins' },
      { front: 'Milwaukee Brewers', back: 'Milwaukee Brewers' },
      { front: 'Minnesota Twins', back: 'Minnesota Twins' },
      { front: 'New York Yankees', back: 'New York Yankees' },
      { front: 'New York Mets', back: 'New York Mets' },
      { front: 'Athletics', back: 'Athletics' },
      { front: 'Philadelphia Phillies', back: 'Philadelphia Phillies' },
      { front: 'Pittsburgh Pirates', back: 'Pittsburgh Pirates' },
      { front: 'San Diego Padres', back: 'San Diego Padres' },
      { front: 'San Francisco Giants', back: 'San Francisco Giants' },
      { front: 'Seattle Mariners', back: 'Seattle Mariners' },
      { front: 'St. Louis Cardinals', back: 'St. Louis Cardinals' },
      { front: 'Tampa Bay Rays', back: 'Tampa Bay Rays' },
      { front: 'Texas Rangers', back: 'Texas Rangers' },
      { front: 'Toronto Blue Jays', back: 'Toronto Blue Jays' },
      { front: 'Washington Nationals', back: 'Washington Nationals' }
    ]
  },
  {
    front: 'NHL',
    back: 'nhl',
    teams: [
      { front: 'Anaheim Ducks', back: 'Anaheim Ducks' },
      { front: 'Arizona Coyotes', back: 'Arizona Coyotes' },
      { front: 'Boston Bruins', back: 'Boston Bruins' },
      { front: 'Buffalo Sabres', back: 'Buffalo Sabres' },
      { front: 'Calgary Flames', back: 'Calgary Flames' },
      { front: 'Carolina Hurricanes', back: 'Carolina Hurricanes' },
      { front: 'Chicago Blackhawks', back: 'Chicago Blackhawks' },
      { front: 'Colorado Avalanche', back: 'Colorado Avalanche' },
      { front: 'Columbus Blue Jackets', back: 'Columbus Blue Jackets' },
      { front: 'Dallas Stars', back: 'Dallas Stars' },
      { front: 'Detroit Red Wings', back: 'Detroit Red Wings' },
      { front: 'Edmonton Oilers', back: 'Edmonton Oilers' },
      { front: 'Florida Panthers', back: 'Florida Panthers' },
      { front: 'Los Angeles Kings', back: 'Los Angeles Kings' },
      { front: 'Minnesota Wild', back: 'Minnesota Wild' },
      { front: 'Montreal Canadiens', back: 'Montreal Canadiens' },
      { front: 'Nashville Predators', back: 'Nashville Predators' },
      { front: 'New Jersey Devils', back: 'New Jersey Devils' },
      { front: 'New York Islanders', back: 'New York Islanders' },
      { front: 'New York Rangers', back: 'New York Rangers' },
      { front: 'Ottawa Senators', back: 'Ottawa Senators' },
      { front: 'Philadelphia Flyers', back: 'Philadelphia Flyers' },
      { front: 'Pittsburgh Penguins', back: 'Pittsburgh Penguins' },
      { front: 'San Jose Sharks', back: 'San Jose Sharks' },
      { front: 'Seattle Kraken', back: 'Seattle Kraken' },
      { front: 'St. Louis Blues', back: 'St. Louis Blues' },
      { front: 'Tampa Bay Lightning', back: 'Tampa Bay Lightning' },
      { front: 'Toronto Maple Leafs', back: 'Toronto Maple Leafs' },
      { front: 'Vancouver Canucks', back: 'Vancouver Canucks' },
      { front: 'Vegas Golden Knights', back: 'Vegas Golden Knights' },
      { front: 'Washington Capitals', back: 'Washington Capitals' },
      { front: 'Winnipeg Jets', back: 'Winnipeg Jets' }
    ]
  }
];